### ISSUE TITLE
Version Appending

### ISSUE THREAD

**Issue by franton** [autopkg/tbridge-recipes#2]
Hi Tom,

Any chance you can have autopkg append the version of NoMAD to the end of the files it produces?

**Comment by tbridge** [comment]
Hi Richard,

Thanks for writing in and for chatting about your issue on Slack! If you'd like a version that appends the version, I would recommend forking this recipe. We need the plain package for a couple different reasons, and because of that, I'm going to close this issue with a #wontfix. Nothing personal, this recipe just is this way for a reason.
